# Generated by Django 4.0.2 on 2023-08-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tag_alter_product_owner_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Banner',
            field=models.ImageField(default='/staticfiles/images/latest-1.jpg', upload_to='cat-img/banner/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/staticfiles/images/latest-1.jpg', upload_to='cat-img/'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
