# Generated by Django 4.0.2 on 2023-08-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_banner_category_image_remove_product_cat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='tag',
        ),
    ]
