# Generated by Django 4.0.2 on 2023-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
