# Generated by Django 4.0.2 on 2023-08-13 15:48

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_user'),
        ('products', '0009_remove_review_value_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Banner',
            field=models.ImageField(default='/staticfiles/images/latest-1.jpg', null=True, upload_to='cat-img/banner/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/staticfiles/images/latest-1.jpg', null=True, upload_to='cat-img/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
