# Generated by Django 4.0.2 on 2023-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_remove_order_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(default='paypal', max_length=200),
        ),
    ]
