# Generated by Django 4.0.2 on 2023-11-13 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('lasttname', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField()),
                ('tel', models.CharField(blank=True, max_length=11, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
